name: Build OnePlus 8T Docker Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/LineageOS/android_kernel_oneplus_sm8250
          kernel-branch: lineage-23.2

          config: vendor/kona-perf_defconfig
          arch: arm64
          vendor: false
          kernel-dir: .

          android-version:

          aosp-gcc: false
          aosp-clang: false

          lxc: true
          lxc-patch: true
          anykernel3: true

          extra-make-args: '[
            "LLVM=1",
            "LLVM_IAS=1",
            "KCFLAGS=-w",
            "WERROR=0"
          ]'
